services:
  db:
    build: DB_dockerDir/
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      # Recommendation: avoid defining a named volume (and let docker compose manage all for you) or use a tmpfs.
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local
